[project]
name = "LTXDirector-Extender"
description = "Fork of WhatDreamsCost-ComfyUI focused on tested LTX Director extension fixes."
version = "1.3.2"
license = {file = "LICENSE"} 
requires-python = ">=3.10"
classifiers = [
	"Operating System :: OS Independent",
]


[project.urls]
Repository = "https://github.com/Yogurt1192/LTXDirector-Extender"
Documentation = "https://github.com/Yogurt1192/LTXDirector-Extender"
"Bug Tracker" = "https://github.com/Yogurt1192/LTXDirector-Extender/issues"

[tool.comfy]
PublisherId = "yogurt1192"
DisplayName = "LTXDirector-Extender"
Icon = "https://raw.githubusercontent.com/Yogurt1192/LTXDirector-Extender/main/images/YogurtMan400.png"
requires-comfyui = ">=0.22.1,<0.23.0"
includes = [] 


